### ISSUE TITLE
Bug: FPS drop extremly on talking

### ISSUE THREAD

**Issue by mathexresources** [acscripts/ac_radio#10]
### Version

1.0.7 (newest)

### Issue description

whenever i press talk key the FPS drop from 60 to 15 fps for a second, it hapens to everybody on the server, i use esx legacy with overextended and pma voice

### Steps to reproduce

1. Connect a channel
2. Try to talk

**Comment by antond15** [comment]
Can't reproduce it on ESX, QB or OX server.
This must be an issue with some of your scripts, probably have some loop associated with the same keybind. Try to change the keybind if it still happens.

**Comment by antond15** [comment]
This resource has nothing to do with the "radio talk" function. All of the voice stuff happens in pma-voice.

**Comment by mathexresources** [comment]
i tried reinstall the script and it seems to be working
