### ISSUE TITLE
Bug: Item can not be used

### ISSUE THREAD

**Issue by onscripts** [acscripts/ac_radio#11]
### Version

1.0.8

### Issue description

When you have the radio item in ox_inventory and qb-core it gives an error and doesnt do anything

### Steps to reproduce

1. get a radio item
2. use it via ox_inventory
3. see error

**Comment by antond15** [comment]
Maybe show the error?

**Comment by antond15** [comment]
@zZOGZz

**Comment by antond15** [comment]
Unable to provide details.
