### ISSUE TITLE
Bug: Restricted Radio Channels

### ISSUE THREAD

**Issue by jswxxx** [acscripts/ac_radio#12]
### Version

latest (1.0.8)

### Framework

es_extended

### Issue description

I need help abt Restrict Radio Channels coz its not working on my side. 

Config (Restrict Side)
	-- Number of available frequencies.
	maximumFrequencies = 1000,

	-- How much the frequency value can change per step.
	frequencyStep = 0.01,

	-- Channel frequency restrictions.
	restrictedChannels = {
		[1] = 'police',
		[2] = {
			ambulance = 0      
		},
		[3] = {
			mechanic = 0      
		},
		[4] = {
			police = 0,
			ambulance = 0
		},
		[5] = {
			police = 0,
			mechanic = 0
		},
	},

Direct Vid: https://streamable.com/ztojnh

### Steps to reproduce

Nothing, just fix this please. Thank you

### Confirm the following statements:

- [X] This issue is not a question or a feature request.
- [ ] I have provided a **detailed** issue description and **detailed** reproduction steps.

**Comment by antond15** [comment]
> **Steps to reproduce**
Nothing, just fix this please. Thank you

Useful, thanks.
