### ISSUE TITLE
Enhancement: Multiple radios at a time

### ISSUE THREAD

**Issue by Kraleemil** [acscripts/ac_radio#16]
### Feature description

Can there be able to use 2 or more radios at a time. Like when you are at a scene, and wants to hear the ems radio and fire for command.

### Reason

I think it's needed at a big scene, or internal coms and main at the same time

**Comment by antond15** [comment]
It's not possible.
The correct place to request this feature is [pma-voice](https://github.com/AvarianKnight/pma-voice). ac_radio is basically just a visual wrapper for it's radio functions.
