### ISSUE TITLE
Bug: Radio UI opens automatically

### ISSUE THREAD

**Issue by mstigl** [acscripts/ac_radio#25]
### Version

v1.2.0

### Framework

es_extended

### Issue description

When I switch the windows from the FiveM window to another window and then I get back to the FiveM one, the radio UI shows up without having set any keybind, is that normal or it's a bug? Am I the only one having that bug?
Thanks

### Steps to reproduce

(When ac_radio and pma-voice installed in server, of course)
1. Switch window from the FiveM window to another one (using mouse or ALT+TAB)
2. Get back to FiveM window, it will show up the radio UI without clicking anything

### Confirm the following statements:

- [X] This issue is not a question or a feature request.
- [X] I have provided a **detailed** issue description and **detailed** reproduction steps.

**Comment by antond15** [comment]
Can't reproduce it. Are you sure you have no keybind set for the `/radio` command?

**Comment by mstigl** [comment]
I had to change the command name to something like `/openradio` because with the `/radio` command I have that problem.
I also check that I don't have any keybind assigned to that. What should I do?

**Comment by antond15** [comment]
`/radio` might be already used by some other resource.
The default keybind is named **default** for a reason. If you've already unbound the command, then it won't change.
