### ISSUE TITLE
Bug: Radio volume buttons

### ISSUE THREAD

**Issue by Saltylord** [acscripts/ac_radio#29]
### Version

v2.0.0

### Framework

qb-core

### Issue description

When using the volume up and down buttons the volume up button will display the notification that the volume went up by 10% but the value remains the same. Also the volume down button is continuing to tell you the volume is at the lowest but again the value remains the same. Thank you

https://streamable.com/kbrxug

### Steps to reproduce

1. Open radio
2. Use volume up button a few times
3. Use volume down button a few times

### Confirm the following statements:

- [X] This issue is not a question or a feature request.
- [X] I have provided a **detailed** issue description and **detailed** reproduction steps.
- [X] I have read the documentation.

**Comment by antond15** [comment]
You're not using the latest pma-voice. Either download it youself as a source code or use my [fork](https://github.com/acscripts/pma-voice) with latest release.

**Comment by Saltylord** [comment]
Ahh thank you

**Comment by antond15** [comment]
This is there for a reason.
![image](https://github.com/acscripts/ac_radio/assets/71350868/a623c876-f056-492c-9276-625fc05796ff)

**Comment by Saltylord** [comment]
yep my bad
