### ISSUE TITLE
Distance effects and battery

### ISSUE THREAD

**Issue by TheZahamar** [acscripts/ac_radio#8]
### Feature description

Add, if you’re ever further away from the people on the radio, the radio starts to rustle and stop until at the end, when someone speaks, it’s just a rustle.

The second option is to add batteries to the radio of course not for groups with factions like: police, medicine

### Reason

I think it’s a cool addition to RolePlay

**Comment by antond15** [comment]
The range sounds interesting, but I probably won't do it. There are stuff like terrain (hills, buildings, plains/roads) or map size that have to be taken into mind.

**Comment by TheZahamar** [comment]
Rather, it is only about the distance between people e. g. radio runs at 2 miles apart

**Comment by antond15** [comment]
Batteries are something I've wanted to do for a long time, but never got to it.
Thinking about it - I want this feature, so when I find some time later this week, I'll try it.

**Comment by TheZahamar** [comment]
That would be great, I’ve been looking for such a script for advice for a long time.
